[0m18:52:20.297657 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7955bf629ed0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7955be5b8190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7955be5b8130>]}


============================== 18:52:20.305387 | e21eb722-eaf8-4ee9-8cdb-cb8069dce3ab ==============================
[0m18:52:20.305387 [info ] [MainThread]: Running with dbt=1.10.11
[0m18:52:20.306971 [debug] [MainThread]: running dbt with arguments {'log_cache_events': 'False', 'version_check': 'True', 'static_parser': 'True', 'empty': 'None', 'fail_fast': 'False', 'invocation_command': 'dbt init', 'write_json': 'True', 'introspect': 'True', 'partial_parse': 'True', 'profiles_dir': '/root/.dbt', 'cache_selected_only': 'False', 'use_colors': 'True', 'quiet': 'False', 'indirect_selection': 'eager', 'log_format': 'default', 'printer_width': '80', 'use_experimental_parser': 'False', 'debug': 'False', 'log_path': 'logs', 'target_path': 'None', 'send_anonymous_usage_stats': 'True', 'no_print': 'None', 'warn_error': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])'}
[0m18:52:20.325034 [info ] [MainThread]: Creating dbt configuration folder at /root/.dbt
[0m18:54:14.970504 [debug] [MainThread]: Starter project path: /usr/local/lib/python3.10/site-packages/dbt/include/starter_project
[0m18:54:15.092655 [info ] [MainThread]: 
Your new dbt project "source_to_analytics" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:54:15.093685 [info ] [MainThread]: Setting up your profile.
[0m18:54:21.911748 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m18:54:21.913051 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m18:54:21.913942 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m19:00:41.608787 [info ] [MainThread]: Profile source_to_analytics written to /root/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m19:00:41.623129 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 501.4122, "process_in_blocks": "80120", "process_kernel_time": 0.153996, "process_mem_max_rss": "100324", "process_out_blocks": "40", "process_user_time": 1.127919}
[0m19:00:41.625744 [debug] [MainThread]: Command `dbt init` succeeded at 19:00:41.625530 after 501.42 seconds
[0m19:00:41.627575 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7955bf629ed0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7955be6100a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7955be56b640>]}
[0m19:00:41.629114 [debug] [MainThread]: Flushing usage events
[0m19:00:42.993912 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:01:00.600298 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7639c13a5f30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7639c0324250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7639c0324160>]}


============================== 19:01:00.603196 | 5f4a10de-cd21-4baa-b756-5ef2325ac92d ==============================
[0m19:01:00.603196 [info ] [MainThread]: Running with dbt=1.10.11
[0m19:01:00.604455 [debug] [MainThread]: running dbt with arguments {'introspect': 'True', 'write_json': 'True', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'empty': 'None', 'invocation_command': 'dbt debug', 'target_path': 'None', 'log_cache_events': 'False', 'cache_selected_only': 'False', 'log_format': 'default', 'use_colors': 'True', 'send_anonymous_usage_stats': 'True', 'version_check': 'True', 'fail_fast': 'False', 'debug': 'False', 'partial_parse': 'True', 'quiet': 'False', 'static_parser': 'True', 'use_experimental_parser': 'False', 'log_path': 'logs', 'indirect_selection': 'eager', 'printer_width': '80', 'warn_error': 'None', 'profiles_dir': '/root/.dbt'}
[0m19:01:00.622815 [info ] [MainThread]: dbt version: 1.10.11
[0m19:01:00.624152 [info ] [MainThread]: python version: 3.10.18
[0m19:01:00.625253 [info ] [MainThread]: python path: /usr/local/bin/python3.10
[0m19:01:00.626458 [info ] [MainThread]: os info: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.41
[0m19:01:00.663114 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m19:01:00.664490 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m19:01:00.665484 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m19:01:00.694408 [info ] [MainThread]: Using profiles dir at /root/.dbt
[0m19:01:00.696056 [info ] [MainThread]: Using profiles.yml file at /root/.dbt/profiles.yml
[0m19:01:00.697450 [info ] [MainThread]: Using dbt_project.yml file at /app/dbt_project.yml
[0m19:01:00.698900 [info ] [MainThread]: Configuration:
[0m19:01:00.700016 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m19:01:00.701389 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m19:01:00.702921 [info ] [MainThread]: Required dependencies:
[0m19:01:00.704398 [debug] [MainThread]: Executing "git --help"
[0m19:01:00.706599 [info ] [MainThread]:  - git [[31mERROR[0m]

[0m19:01:00.708116 [info ] [MainThread]: Connection test skipped since no profile was found
[0m19:01:00.709343 [info ] [MainThread]: [31m3 checks failed:[0m
[0m19:01:00.710550 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "source_to_analytics", target "dev" invalid: Runtime Error
    http connection method requires additional dependencies. 
    Install the additional required dependencies with `pip install dbt-spark[PyHive]`


[0m19:01:00.711706 [info ] [MainThread]: Project loading failed for the following reason:
 project path </app/dbt_project.yml> not found

[0m19:01:00.713013 [info ] [MainThread]: Error from git --help: Could not find command, ensure it is in the user's PATH: "git"

[0m19:01:00.714784 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.16693494, "process_in_blocks": "40", "process_kernel_time": 0.071927, "process_mem_max_rss": "101156", "process_out_blocks": "8", "process_user_time": 1.038957}
[0m19:01:00.715862 [debug] [MainThread]: Command `dbt debug` failed at 19:01:00.715700 after 0.17 seconds
[0m19:01:00.716938 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7639c13a5f30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7639c0324190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7639c03239a0>]}
[0m19:01:00.718267 [debug] [MainThread]: Flushing usage events
[0m19:01:02.036603 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:13:43.988453 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7185c26f5e10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7185c1674220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7185c16741c0>]}


============================== 19:13:43.994598 | 84a25f20-bbf9-4553-b443-ca8d634a24b4 ==============================
[0m19:13:43.994598 [info ] [MainThread]: Running with dbt=1.10.11
[0m19:13:43.996060 [debug] [MainThread]: running dbt with arguments {'static_parser': 'True', 'no_print': 'None', 'log_cache_events': 'False', 'use_colors': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True', 'log_path': 'logs', 'profiles_dir': '/root/.dbt', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'quiet': 'False', 'use_experimental_parser': 'False', 'cache_selected_only': 'False', 'log_format': 'default', 'introspect': 'True', 'indirect_selection': 'eager', 'partial_parse': 'True', 'invocation_command': 'dbt debug', 'version_check': 'True', 'write_json': 'True', 'empty': 'None', 'debug': 'False', 'warn_error': 'None', 'printer_width': '80', 'fail_fast': 'False'}
[0m19:13:44.012868 [info ] [MainThread]: dbt version: 1.10.11
[0m19:13:44.014185 [info ] [MainThread]: python version: 3.10.18
[0m19:13:44.015861 [info ] [MainThread]: python path: /usr/local/bin/python3.10
[0m19:13:44.016994 [info ] [MainThread]: os info: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.41
[0m19:13:44.018149 [info ] [MainThread]: Using profiles dir at /root/.dbt
[0m19:13:44.019538 [info ] [MainThread]: Using profiles.yml file at /root/.dbt/profiles.yml
[0m19:13:44.020945 [info ] [MainThread]: Using dbt_project.yml file at /app/dbt_project.yml
[0m19:13:44.022620 [info ] [MainThread]: Configuration:
[0m19:13:44.023772 [info ] [MainThread]:   profiles.yml file [[31mERROR not found[0m]
[0m19:13:44.025124 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m19:13:44.026393 [info ] [MainThread]: Required dependencies:
[0m19:13:44.027858 [debug] [MainThread]: Executing "git --help"
[0m19:13:44.030238 [info ] [MainThread]:  - git [[31mERROR[0m]

[0m19:13:44.031770 [info ] [MainThread]: Connection test skipped since no profile was found
[0m19:13:44.033106 [info ] [MainThread]: [31m3 checks failed:[0m
[0m19:13:44.034437 [info ] [MainThread]: dbt looked for a profiles.yml file in /root/.dbt/profiles.yml, but did
not find one. For more information on configuring your profile, consult the
documentation:

https://docs.getdbt.com/docs/configure-your-profile


[0m19:13:44.035657 [info ] [MainThread]: Project loading failed for the following reason:
 project path </app/dbt_project.yml> not found

[0m19:13:44.036764 [info ] [MainThread]: Error from git --help: Could not find command, ensure it is in the user's PATH: "git"

[0m19:13:44.039041 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.10318435, "process_in_blocks": "880", "process_kernel_time": 0.069426, "process_mem_max_rss": "95532", "process_out_blocks": "32", "process_user_time": 0.922961}
[0m19:13:44.040134 [debug] [MainThread]: Command `dbt debug` failed at 19:13:44.040027 after 0.10 seconds
[0m19:13:44.041007 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7185c26f5e10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7185c1626080>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7185c16aa7a0>]}
[0m19:13:44.041947 [debug] [MainThread]: Flushing usage events
[0m19:13:45.375688 [debug] [MainThread]: An error was encountered while trying to flush usage events
